방문한 페이지 등록 요청
LM-channel-team-project/kiwee.dev pull request #39
Opened 2021-05-28 04:35 UTC by 97baek

## 개요 🪧

- 방문한 페이지 등록 요청 (PATCH)
 
## 작업 내용 📄

- isVisited가 false인 article을 클릭했을 때, /history에 articleId를 담은 쿼리문을 보냅니다.

## 변경 로직 ⚙️

- X

## 스크린샷 📸
![image](https://user-images.githubusercontent.com/73068489/119930021-9d122880-bfb9-11eb-97b8-e961493782f8.png)

2021-05-28 06:46 UTC, euntaek requested changes
CardImage 컴포넌트와 CardContent 컴포넌트의 href, onClick를 
a tag 하나로 통합 하는 게 좋을 거 같습니다.
새로운 탭에서 열기 기능은 CardImage 컴포넌트만 설정되어 있습니다.

2021-05-28 07:04 UTC, 97baek commented
> CardImage 컴포넌트와 CardContent 컴포넌트의 href, onClick를
> a tag 하나로 통합 하는 게 좋을 거 같습니다.
> 새로운 탭에서 열기 기능은 CardImage 컴포넌트만 설정되어 있습니다.

아 그렇네요 확인했습니다! 

수정해서 커밋 올리겠습니다. 감사합니다!

2021-05-29 05:31 UTC, euntaek approved these changes

2021-05-30 06:49 UTC, Jungho-Cheon approved these changes
확인했습니다~!

2021-05-30 06:50 UTC, merged